### ISSUE TITLE
UnsupportedOperationException crash on IntelliJ IDEA 2024.2 Beta

### ISSUE THREAD

**Issue by VojtaStanek** [patricklx/intellij-wsl-symlinks#13]
### Description

Following crash: 

```
java.lang.UnsupportedOperationException: VirtualFile: \\wsl.localhost\Ubuntu\\angular.json
	at com.intellij.openapi.vfs.newvfs.impl.StubVirtualFile.unsupported(StubVirtualFile.java:217)
	at com.intellij.openapi.vfs.newvfs.impl.StubVirtualFile.getName(StubVirtualFile.java:56)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemImpl.getAttributes(LocalFileSystemImpl.java:323)
	at com.wsl.symlinks.vfs.WslVirtualFileSystem.getAttributes(WslVirtualFileSystem.kt:291)
	at com.intellij.openapi.vfs.newvfs.RefreshWorker.lambda$computeAttributesForFile$5(RefreshWorker.java:400)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:62)
	at com.intellij.openapi.vfs.newvfs.RefreshWorker.computeAttributesForFile(RefreshWorker.java:400)
	at com.intellij.openapi.vfs.newvfs.RefreshWorker.getAttributes(RefreshWorker.java:385)
	at com.intellij.openapi.vfs.newvfs.RefreshWorker.partialDirRefresh(RefreshWorker.java:335)
	at com.intellij.openapi.vfs.newvfs.RefreshWorker.processQueue(RefreshWorker.java:187)
	at com.intellij.openapi.vfs.newvfs.RefreshWorker.lambda$parallelScan$0(RefreshWorker.java:123)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

```

### Steps to Reproduce

Just open project... 

### Versions
```
IntelliJ IDEA 2024.2 Beta (Ultimate Edition)
Build #IU-242.20224.91, built on July 18, 2024
Licensed to IntelliJ IDEA EAP user: Vojta Staněk
Expiration date: August 17, 2024
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
Kotlin analyzer version: 2.0.20-ij242-13
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
  debugger.watches.in.variables=false
  ide.experimental.ui=true
  terminal.new.ui=true
  ide.images.show.chessboard=true
  editor.minimap.enabled=true
  org.toml.json.schema=false
  eslint.additional.file.extensions=svelte
Non-Bundled Plugins:
  Batch Scripts Support (1.0.13)
  com.jetbrains.rust (242.19890.39)
  com.wsl.symlinks (2024.2.1)
  com.markskelton.one-dark-theme (5.11.0)
  String Manipulation (9.14.1)
  dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
  org.jetbrains.plugins.go (242.20224.91)
  com.intellij.plugin.adernov.powershell (2.6.1)
  com.intellij.nativeDebug (242.20224.23)
  org.jetbrains.plugins.gitlab (242.20224.99)
  org.jetbrains.plugins.github (242.20224.99)
  Dart (242.20629)
  io.pivotal.jasmine (1.9)
  com.intellij.lang.jsgraphql (242.20224.22)
  dev.blachut.svelte.lang (242.20224.23)
  com.jetbrains.packagesearch.intellij-plugin (242.0.12)
  org.jetbrains.android (242.20224.91)
  mobi.hsz.idea.gitignore (4.5.3)
  com.jetbrains.php (242.20224.112)
  com.jetbrains.twig (242.20224.112)
  ru.adelf.idea.dotenv (2024.2)
  com.github.copilot (1.5.16.6140)
Kotlin: 242.20224.91-IJ
```

**Comment by patricklx** [comment]
hi, this has been fixed in https://github.com/patricklx/intellij-wsl-symlinks/commit/c5ef1d1b2e303b0e068bee6eb737df610b322ab6

and is awaiting intellij approval for upload.

**Comment by VojtaStanek** [comment]
Awesome! Do you possibly have a jar (install plugin from disk) for me to test?

**Comment by patricklx** [comment]
sure
[intellij-wsl-symlinks-2024.2.2.zip](https://github.com/user-attachments/files/16346369/intellij-wsl-symlinks-2024.2.2.zip)

**Comment by patricklx** [comment]
i fixed the CI to upload the build. you can find it here at the bottom:
https://github.com/patricklx/intellij-wsl-symlinks/actions/runs/10056614167
